#!/usr/bin/env bash
# Enforce that SDK model/types are generated from intentproof-spec (no handwritten schema models).
# Usage: check-sdk-no-handwritten-model-types.sh /absolute/path/to/sdk-repo
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: check-sdk-no-handwritten-model-types.sh /absolute/path/to/sdk-repo" >&2
  exit 2
fi

sdk_root="$(cd "$1" && pwd)"

if [[ -f "${sdk_root}/packages/sdk/package.json" ]]; then
  python3 - "${sdk_root}" <<'PY'
import pathlib
import re
import sys

sdk_root = pathlib.Path(sys.argv[1])
sdk_src = sdk_root / "packages" / "sdk" / "src"
generated_root = sdk_src / "generated"
bridge = sdk_src / "types.ts"

generated_header_markers = (
    "automatically generated by json-schema-to-typescript",
    "Generated by scripts/embed-spec-schemas.mjs",
)
forbidden_model_names = (
    "IntentProofExecutionEventV1",
    "ExecutionError",
    "ExecutionError1",
    "IntentProofWrapOptionsV1",
    "IntentProofRuntimeConfigV1",
)

def strip_comments_and_strings(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//.*?$", "", text, flags=re.M)
    text = re.sub(r'"(?:\\.|[^"\\])*"', '""', text)
    text = re.sub(r"'(?:\\.|[^'\\])*'", "''", text)
    return text

errors = []
for path in sorted(sdk_src.rglob("*.ts")):
    rel = path.relative_to(sdk_root).as_posix()
    text = path.read_text(encoding="utf-8")

    if path.is_relative_to(generated_root):
        if not any(marker in text for marker in generated_header_markers):
            errors.append(f"{rel}: missing generated-file marker comment")
        continue

    for name in forbidden_model_names:
        if re.search(rf"\b(?:export\s+)?(?:interface|type|class)\s+{name}\b", text):
            errors.append(f"{rel}: handwritten declaration for generated model/type {name}")
            break

bridge_text = strip_comments_and_strings(bridge.read_text(encoding="utf-8"))
bridge_rules = (
    r"\bexport\s+type\s+ExecutionStatus\s*=\s*IntentProofExecutionEventV1\[[^\]]+\]\s*;",
    r"\bexport\s+type\s+ExecutionErrorSnapshot\s*=\s*Readonly<ExecutionError>\s*;",
    r"\bexport\s+type\s+ExecutionEvent\s*=\s*Readonly<IntentProofExecutionEventV1>\s*;",
)
for rule in bridge_rules:
    if not re.search(rule, bridge_text):
        errors.append(
            "packages/sdk/src/types.ts: expected generated-type bridge aliases were changed (ExecutionEvent/ExecutionErrorSnapshot/ExecutionStatus)"
        )
        break

if errors:
    print("check-sdk-no-handwritten-model-types: found forbidden handwritten model/type definitions:", file=sys.stderr)
    for err in errors:
        print(f" - {err}", file=sys.stderr)
    sys.exit(1)

print("OK: model/types are spec-generated (no handwritten model definitions outside packages/sdk/src/generated)")
PY
elif [[ -f "${sdk_root}/pyproject.toml" ]]; then
  python3 - "${sdk_root}" <<'PY'
import pathlib
import re
import sys

sdk_root = pathlib.Path(sys.argv[1])
root = sdk_root / "src" / "intentproof"
generated_root = root / "generated"
bridge = root / "types.py"

forbidden_class_names = (
    "ExecutionError",
    "IntentProofExecutionEventV1",
    "IntentProofRuntimeConfigV1",
    "WrapOptionsV1",
)

def strip_comments_and_strings(text: str) -> str:
    text = re.sub(r'"""[\s\S]*?"""', "", text)
    text = re.sub(r"'''[\s\S]*?'''", "", text)
    text = re.sub(r"#.*?$", "", text, flags=re.M)
    text = re.sub(r'"(?:\\.|[^"\\])*"', '""', text)
    text = re.sub(r"'(?:\\.|[^'\\])*'", "''", text)
    return text

errors = []
for path in sorted(root.rglob("*.py")):
    rel = path.relative_to(sdk_root).as_posix()
    text = path.read_text(encoding="utf-8")
    norm = strip_comments_and_strings(text)

    if path.is_relative_to(generated_root):
        lowered = text.lower()
        if (
            "generated by datamodel-codegen" not in lowered
            and "generated by scripts/generate_schema_models.py" not in lowered
            and "(generated)" not in lowered
            and "do not edit by hand" not in lowered
        ):
            errors.append(f"{rel}: missing generated-file marker comment")
        continue

    for name in forbidden_class_names:
        if re.search(rf"\bclass\s+{name}\b", norm):
            errors.append(f"{rel}: handwritten class declaration for generated model/type {name}")
            break

bridge_text = strip_comments_and_strings(bridge.read_text(encoding="utf-8"))
for rule in (r"\bExecutionEvent\s*=\s*IntentProofExecutionEventV1\b", r"\bExecutionErrorSnapshot\s*=\s*ExecutionError\b"):
    if not re.search(rule, bridge_text):
        errors.append(
            "src/intentproof/types.py: expected generated-type bridge aliases were changed (ExecutionEvent/ExecutionErrorSnapshot)"
        )
        break

if errors:
    print("check-sdk-no-handwritten-model-types: found forbidden handwritten model/type definitions:", file=sys.stderr)
    for err in errors:
        print(f" - {err}", file=sys.stderr)
    sys.exit(1)

print("OK: model/types are spec-generated (no handwritten model classes outside src/intentproof/generated)")
PY
elif [[ -f "${sdk_root}/build.gradle.kts" ]]; then
  python3 - "${sdk_root}" <<'PY'
import pathlib
import re
import sys

sdk_root = pathlib.Path(sys.argv[1])
root = sdk_root / "src" / "main" / "java" / "com" / "intentproof" / "sdk"
generated_root = root / "generated" / "v1"
bridge = root / "ExecutionEvent.java"

model_annotation_markers = (
    "@JsonProperty(",
    "@JsonPropertyDescription(",
    "@JsonPropertyOrder(",
    "@JsonInclude(",
    "@JsonAnyGetter",
    "@JsonAnySetter",
    "@JsonCreator",
)

def strip_comments_and_strings(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//.*?$", "", text, flags=re.M)
    text = re.sub(r'"(?:\\.|[^"\\])*"', '""', text)
    return text

errors = []
for path in sorted(root.rglob("*.java")):
    rel = path.relative_to(sdk_root).as_posix()
    text = path.read_text(encoding="utf-8")

    if path.is_relative_to(generated_root):
        if '@Generated("jsonschema2pojo")' not in text:
            errors.append(f"{rel}: generated model missing @Generated(\"jsonschema2pojo\") marker")
        continue

    for marker in model_annotation_markers:
        if marker in text:
            errors.append(f"{rel}: contains model annotation marker {marker} outside generated/v1")
            break

    if "extends com.intentproof.sdk.generated.v1." in text or "extends IntentProofExecutionEventV1" in text:
        if path != bridge:
            errors.append(f"{rel}: extends generated model type outside allowed bridge")

bridge_pattern = re.compile(
    r"public\s+class\s+ExecutionEvent\s+extends\s+com\.intentproof\.sdk\.generated\.v1\.IntentProofExecutionEventV1\s*\{\s*\}",
    flags=re.S,
)
if not bridge_pattern.search(strip_comments_and_strings(bridge.read_text(encoding="utf-8"))):
    errors.append(
        "src/main/java/com/intentproof/sdk/ExecutionEvent.java: bridge must remain an empty subclass of generated IntentProofExecutionEventV1"
    )

if errors:
    print("check-sdk-no-handwritten-model-types: found forbidden handwritten model/type definitions:", file=sys.stderr)
    for err in errors:
        print(f" - {err}", file=sys.stderr)
    sys.exit(1)

print("OK: model/types are spec-generated (no handwritten model classes outside generated/v1)")
PY
else
  echo "check-sdk-no-handwritten-model-types: could not detect SDK type at ${sdk_root}" >&2
  exit 2
fi
